### PR TITLE
Configure such that ' package' puts jars into ~/sbtUnmanagedJars, to be ...

### PR DESCRIPTION
**Pull request by erikerlandson**
...available to other projects from local builds

### CODE REVIEW

**Comment by willb** [comment]
This is surprising behavior (since `sbt package` usually does something else).  Can you make deploying unmanaged jars a different task instead?

**Comment by erikerlandson** [comment]
Should be straightforward to make a 'packageLocal' task, or some such

**Comment by erikerlandson** [comment]
Now provided via a plugin

$ sbt packageUnmanaged

destination directory defaults to ~/sbtUnmanagedJars
set with:
packageUnmanaged.unmanagedJarDir := "my/directory/name"

**Comment by willb** [comment]
LGTM, thanks!

**Pull request merged**
